- hosts: default
  user: aoshiman
  become: yes
  gather_facts: no
  roles:
  - sshd
  - timezone-ja
  - locale-ja
  - iptables
  - fail2ban
  - python3-setup
  - virtualenv
  - vimrc
  - screenrc
  - set-blog
