- name: fail2ban | Install fail2ban
  apt: pkg=fail2ban state=latest update_cache=yes

- name: fail2ban | Configure fail2ban local jails
  action: template src=jail.local.j2 dest=/etc/fail2ban/jail.local mode=0644
  notify: restart fail2ban
