- name: Install python3-dev python3-pip
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
  - build-essential
  - python-dev
  - python3-dev
  - python-pip
  - python3-pip

- name: pip install
  pip: name={{ item }} executable=pip2
  with_items:
  - virtualenvwrapper
